---
micronaut:
  application:
    name: employeeorm

---
datasources:
  default:
    url: jdbc:mariadb://localhost:3306/companies
    driverClassName: org.mariadb.jdbc.Driver
    username: root
    password: root
jpa:
  default:
    properties:
      hibernate:
        hbm2ddl:
          auto: update

